import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout/Layout";
import styles from "../styles/Home.module.css";
import LeftButtons from "../components/LeftButtons/LeftButtons";
import Countries from "../components/Countries/Countries";
import MapChart from "../components/Map/MapChart";

import Logo from "../icons/logo.svg";
import Years from "@/components/Years/Years";

export default function Home() {
  const [isBlurred, setIsBlurred] = useState(false);

  const handleButtonClick = () => {
    setIsBlurred((prevIsBlurred) => !prevIsBlurred);
  };
  return (
    <Layout title="Home">
      <Head>
        <title>Aplicatie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.display}>
        <div className={styles.leftBtns}>
          <LeftButtons onButtonClick={handleButtonClick} />
        </div>
        <div className={styles.map}>
          <MapChart isBlurred={isBlurred} />
        </div>
      </div>
    </Layout>
  );
}
