import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout/Layout";
import styles from "../styles/Home.module.css";
import LeftButtons from "../components/LeftButtons/LeftButtons";
import Countries from "../components/Countries/Countries";
import MapChart from "../components/Map/MapChart";

// import MapChart from "../components/Map/MapChart";
// import Map from "../map/uemap.png";
import Logo from "../icons/logo.svg";
import Years from "@/components/Years/Years";

export default function Home() {
  return (
    <Layout title="Home">
      <Head>
        <title>Aplicatie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.display}>
        <div className={styles.leftBtns}>
          <LeftButtons />
        </div>
        <div className={styles.map}>
          <MapChart />
        </div>
      </div>
    </Layout>
  );
}
